---
name: Build
on: [push]
jobs:
  build-latest:
    runs-on: ubuntu-20.04
    needs: [test]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Parse git ref
        run: |
          echo "DOCKER_TAG_NAME=$(basename $GITHUB_REF)" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN}}

      - name: Build and push Docker image
        run: make docker-release
